name: Bug report
description: Report an issue or bug with Redactive platform
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe what you see!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Fetch a '...'
        2. Update the '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: Bash
    validations:
      required: false
  - type: dropdown
    id: infrastructure
    attributes:
      label: Infrastructure
      description: What infrastructure are you running with?
      options:
        - Google Cloud
        - AWS Cloud
        - Local with Docker container
        - Local
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you using? You may select more than one.
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    id: sdk
    attributes:
      label: SDK
      description: What SDK you are using?
      options:
        - Python SDK
        - Node SDK
        - Other
    validations:
      required: false
  - type: input
    id: sdk-version
    attributes:
      label: SDK version
      description: What version of SDK you are using?
      placeholder: e.g. v1.3.0
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: e.g. error logs
    validations:
      required: false
