semi: true
trailingComma: none
printWidth: 120
plugins: ["@ianvs/prettier-plugin-sort-imports"]
importOrder: ["<BUILT_IN_MODULES>", "", "<THIRD_PARTY_MODULES>", "", "^[.]"]
importOrderParserPlugins: ["typescript"]
importOrderTypeScriptVersion: "5.0.0"
